version: "3"

services:
  app:
    build: .
    platform: linux/amd64
    restart: always
    container_name: "blog-ai-backend"
    ports:
      - "3333:3333"
    command: npm run start:dev
    volumes:
      - .:/usr/app
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    container_name: "blog-ai-database"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "blog_ai_db_password"
      POSTGRES_DB: "blog_ai_db_postgres"
    ports:
      - "3003:5432"
volumes:
  pgdata: